# Generated by Django 5.0.2 on 2024-02-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('points_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stronghold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team_color', models.CharField(choices=[('FF0000', 'Red'), ('0000FF', 'Blue'), ('00FF00', 'Green')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stronghold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.stronghold')),
            ],
        ),
        migrations.AddField(
            model_name='stronghold',
            name='controlling_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.team'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=86)),
                ('salt', models.CharField(max_length=24)),
                ('full_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('pts_multiplier', models.FloatField(default=1.0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_earned', models.DateTimeField()),
                ('action_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.action')),
                ('action_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.stronghold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.user')),
            ],
        ),
    ]
